apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: graphql-content
  namespace: api
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: graphql-content
  strategy: 
    type: RollingUpdate 
    rollingUpdate: 
      maxSurge: 2
      maxUnavailable: 0
  template: 
    metadata: 
      labels: 
        app: graphql-content
    spec: 
      containers: 
        - name: graphql-content
          image: crdschurch/crds-graphql-content:$DOCKER_TAG 
          imagePullPolicy: Always 
          ports: 
            - containerPort: 80 
          resources: 
            limits: 
              memory: "2Gi"
              cpu: "700m" 
            requests: 
              memory: "16Mi" 
              cpu: "100m" 
          readinessProbe:
            httpGet:
              path: /.well-known/apollo/server-health
              port: 8003
            initialDelaySeconds: 1
            timeoutSeconds: 3
            successThreshold: 1
            periodSeconds: 3
          env:
            - name: VAULT_ROLE_ID
              value: $VAULT_ROLE_ID
            - name: VAULT_SECRET_ID
              value: $VAULT_SECRET_ID
            - name: CRDS_ENV
              value: $CRDS_ENV
            - name: NEW_RELIC_LICENSE_KEY            
              value: $NR_INSTALL_KEY
