apiVersion: v1 
kind: Service 
metadata: 
  name: crds-graphql-content
  namespace: api
  labels: 
    app: crds-graphql-content
spec: 
  ports: 
  - name: node
    port: 80
    targetPort: 8003
  selector:
    app: graphql-content
