version: '3'
services:
  node:
    image: crdschurch/crds-graphql-content:${DOCKER_TAG:-local}
    build:
      context: ../../
      dockerfile: ./deployment/docker/Dockerfile
    container_name: graphql-content
    ports:
      - 8003:8003
